### ISSUE TITLE
Error on running install

### ISSUE THREAD

**Issue by cbalda** [thecodingmachine/security.simplelogincontroller#1]
Use of undefined constant ROOT_PATH - assumed 'ROOT_PATH' in [application]\src\utils\const.php on line 3

Fatal error: Uncaught exception 'Mouf\MoufException' with message 'Instance 'content.block' does not exist.' in [application]\vendor\mouf\mouf\src\Mouf\MoufManager.php on line 1867

**Comment by moufmouf** [comment]
Should have been fixed for a long looong time. Closing issue.
